apiVersion: v1
kind: Pod
metadata:
  labels:
    agente-jenkins: jenkins-agent-miguel-alarcon
spec:
  containers:
#  - name: jnlp
#    image: jenkins/inbound-agent:latest
#    resources:
#      limits:
#        memory: "256Mi"
#        cpu: "500m"
#      requests:
#        memory: "64Mi"
#        cpu: "50m"
#  - name: node
#    image: node:24-alpine
#    command: ["cat"]
#    tty: true
#    resources:
#      limits:
#        memory: "512Mi"
#        cpu: "500m"
#      requests:
#        memory: "128Mi"
#        cpu: "100m"
#  - name: pnpm
#    image: ghcr.io/pnpm/pnpm:latest
#    command: ["cat"]
#    tty: true
#    resources:
#      limits:
#        memory: "512Mi"
#        cpu: "500m"
#      requests:
#        memory: "16Mi"
#        cpu: "50m"
#  - name: docker
#    image: docker:latest
#    command: ["cat"]
#    tty: true
#    resources:
#      limits:
#        memory: "512Mi"
#        cpu: "500m"
#      requests:
#        memory: "128Mi"
#        cpu: "100m"
#    volumeMounts:
#    - name: app-source
#      mountPath: /var/run/docker.sock
#      name: docker-socket
  - name: node-pnpm
    image: node:24-alpine
    command: ["cat"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "32Mi"
        cpu: "50m"
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ["cat"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "32Mi"
        cpu: "50m"
  - name: buildkit
    image: moby/buildkit:latest
    command: ["cat"]
    tty: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "32Mi"
        cpu: "50m"
    volumeMounts:
    - name: regcred-dh-miguel-alarcon
      mountPath: /docker-configs/dockerhub
      readOnly: true
    - name: regcred-gh-miguel-alarcon
      mountPath: /docker-configs/github
      readOnly: true
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
  - name: regcred-dh-miguel-alarcon
    secret:
      secretName: regcred-dh-miguel-alarcon
      items:
      - key: .dockerconfigjson
        path: config.json
  - name: regcred-gh-miguel-alarcon
    secret:
      secretName: regcred-gh-miguel-alarcon
      items:
      - key: .dockerconfigjson
        path: config.json